---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: account-registration

outputs:
- name: package-output

run:
  path: account-registration/ci/tasks/package.sh

