---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  ACCOUNT_REGISTRATION_URL:

inputs:
- name: account-registration

run:
  path: account-registration/ci/tasks/smoke-test.sh
