---
resources:
- name: account-registration
  type: git
  source:
    uri: https://github.com/sandhyasujathasoman/Registration_App.git   #<----- REPLACE ME
    branch: master

- name: deploy-account-registration
  type: cf
  source:
    api: api.system.cumuluslabs.io        #<----- REPLACE ME
    username: {{cf-user}}
    password: {{cf-password}}
    organization: ssandhya-pal    #<----- REPLACE ME
    space: sandbox        #<----- REPLACE ME
    skip_cert_check: true

jobs:
- name: deploy
  public: true
  plan:
  - get: account-registration
    trigger: true
  - task: package
    file: account-registration/ci/tasks/package.yml
  - put: deploy-account-registration
    params:
      manifest: account-registration/manifest.yml
      path: package-output/account.war

- name: smoke_test
  public: true
  plan:
  - get: account-registration
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: account-registration/ci/tasks/smoke-test.yml
    params:
      ACCOUNT_REGISTRATION_URL: https://account-registration-internetted-bimillennium.apps.cumuluslabs.io #<---- REPLACE ME

